# Generated by Django 4.2 on 2025-01-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('F', 'Fuego'), ('E', 'Electrico'), ('A', 'Agua'), ('P', 'Planta'), ('X', 'Xavi'), ('T', 'Tierra')], max_length=30),
        ),
    ]
