# Generated by Django 4.2 on 2025-01-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('P', 'Planta'), ('E', 'Electrico'), ('F', 'Fuego'), ('A', 'Agua'), ('X', 'Xavi'), ('T', 'Tierra')], max_length=30),
        ),
    ]
