# Generated by Django 4.2 on 2025-01-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0007_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('X', 'Xavi'), ('A', 'Agua'), ('E', 'Electrico'), ('F', 'Fuego'), ('P', 'Planta'), ('T', 'Tierra')], max_length=30),
        ),
    ]
